#!/usr/bin/env python

# echop
# print the paths in a variable by 
# replacing each ':' with a new line
# use either one arg or stdin

from sys import argv, stdin 
#argv is the input args

if len(argv) ==1:    
    #try to read stdin
    print 'reading from stdin (^D to cancel). you might have wanted `echo $PATH | echop`'
    s=stdin.read()
    print '----------------------------------'
elif len(argv) ==2:
    #get first arg
    s=argv[1] #0th is script name
else:
    #error if args don't make sense
    print 'error:\tcall with exactly one argument or use pipe redirection'
    print '\tcalled with %d:'% (len(argv)-1)
    for arg in argv:
        print '\t %s' % arg
    s=""

lines=s.split(':')
if len(lines) == 0:
    print 'no input'
else:
    for line in lines:
        print line
    
