#!/usr/bin/env bash

function relink() {
  if [[ -h "$1" ]]; then
    echo "Relinking $1"
    # Symbolic link? Then recreate.
    rm "$1"
    ln -sn "$2" "$1"
  elif [[ ! -e "$1" ]]; then
    echo "Linking $1"
    ln -sn "$2" "$1"
  else
    echo "$1 exists as a real file, skipping."
  fi
}

cd ~
relink .emacs ~/.dotfiles/emacs
relink .bash_profile ~/.dotfiles/bash_profile
relink .bashrc ~/.dotfiles/bashrc
#relink .gitconfig ~/.dotfiles/git-config
relink .gemrc ~/.dotfiles/gemrc
relink .hgrc ~/.dotfiles/hgrc
relink .irbrc ~/.dotfiles/irbrc
relink .vimrc ~/.dotfiles/vimrc
relink .ackrc ~/.dotfiles/ackrc
relink .vim ~/.dotfiles/vim
relink .bash_aliases ~/.dotfiles/bash_aliases

read -p "include git aliases/setttings (Y/n)?" yn
case $yn in
  [Nn]*) ;;
  * ) source ~/.dotfiles/gitinit;; 
esac

